# Generated by Django 4.2.7 on 2023-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroauditoria',
            old_name='usuario',
            new_name='user',
        ),
    ]
