# Generated by Django 4.2.7 on 2023-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('nav_bar', 'Ver la barra de menú'), ('cubo', 'Generar cubo de ventas'), ('interface', 'Generar interface contable'), ('plano', 'Generar archivo plano'), ('informe_bi', 'Informe Bi'), ('actualizar_base', 'Actualzación de datos'), ('actualizacion_bi', 'Actualizar Bi'), ('admin', 'Ir al Administrador')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfDt',
            fields=[
                ('nbDt', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nmDt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Rango de Fecha')),
                ('txDtIni', models.TextField(blank=True, null=True, verbose_name='Fecha Inicial')),
                ('txDtFin', models.TextField(blank=True, null=True, verbose_name='Fecha Final')),
            ],
            options={
                'verbose_name': 'Configuración Rango de Fecha',
                'verbose_name_plural': 'Configuración Rangos de Fechas',
                'db_table': 'conf_dt',
            },
        ),
        migrations.CreateModel(
            name='ConfEmpresas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nmEmpresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Empresa')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Base')),
                ('nbServerSidis', models.BigIntegerField(blank=True, null=True, verbose_name='Id Servidor Sidis')),
                ('dbSidis', models.CharField(blank=True, max_length=150, null=True, verbose_name='Base de datos Sidis')),
                ('nbServerBi', models.BigIntegerField(blank=True, null=True, verbose_name='Id Servidor PowerBi')),
                ('dbBi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Base de datos Bi')),
                ('txProcedureExtrae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesos sql Extractor')),
                ('txProcedureCargue', models.TextField(blank=True, null=True, verbose_name='Procesos sql del Cargue')),
                ('nmProcedureInterface', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento Interface')),
                ('txProcedureInterface', models.TextField(blank=True, null=True, verbose_name='Procesos sql de Interface')),
                ('nmProcedureExcel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Excel')),
                ('txProcedureExcel', models.TextField(blank=True, null=True, verbose_name='Procesos sql a Excel')),
                ('nmProcedureExcel2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Excel2')),
                ('txProcedureExcel2', models.TextField(blank=True, null=True, verbose_name='Procesos sql a Excel2')),
                ('nmProcedureCsv', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Csv')),
                ('txProcedureCsv', models.TextField(blank=True, null=True, verbose_name='Procesos sql a Csv')),
                ('nmProcedureCsv2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Csv2')),
                ('txProcedureCsv2', models.TextField(blank=True, null=True, verbose_name='Procesos sql a Csv2')),
                ('nmProcedureSql', models.CharField(blank=True, max_length=30, null=True, verbose_name='Procedimiento a Sql')),
                ('txProcedureSql', models.TextField(blank=True, null=True, verbose_name='Procesos sql a Sql')),
                ('report_id_powerbi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Reporte PowerBi')),
                ('dataset_id_powerbi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dataset PowerBi')),
                ('url_powerbi', models.TextField(blank=True, null=True, verbose_name='Url Pública PowerBi')),
                ('estado', models.IntegerField(blank=True, null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración Empresa',
                'verbose_name_plural': 'Configuración Empresas',
                'db_table': 'conf_empresas',
            },
        ),
        migrations.CreateModel(
            name='ConfServer',
            fields=[
                ('nbServer', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id del Servidor')),
                ('nmServer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripción del Servidor')),
                ('hostServer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Host')),
                ('portServer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Puerto')),
                ('nbTipo', models.BigIntegerField(blank=True, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Configuración Servidor',
                'verbose_name_plural': 'Configuración Servidores',
                'db_table': 'conf_server',
            },
        ),
        migrations.CreateModel(
            name='ConfSql',
            fields=[
                ('nbSql', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id del Proceso')),
                ('txSql', models.TextField(blank=True, null=True, verbose_name='Sql Script')),
                ('nmReporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Proceso')),
                ('txTabla', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla de Inserción')),
                ('txDescripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del Proceso')),
                ('nmProcedure_out', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Procedimiento Extractor')),
                ('nmProcedure_in', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Configuración Proceso Sql',
                'verbose_name_plural': 'Configuración Procesos Sql',
                'db_table': 'conf_sql',
            },
        ),
        migrations.CreateModel(
            name='ConfTipo',
            fields=[
                ('nbTipo', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nmUsr', models.CharField(blank=True, max_length=50, null=True, verbose_name='usuario')),
                ('txPass', models.TextField(blank=True, null=True, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Configuración Tipo Servidor',
                'verbose_name_plural': 'Configuración Tipos de Servidores',
                'db_table': 'conf_tipo',
            },
        ),
    ]
